const DBKEY='awo_hybrid_final_db_v1', SESSIONKEY='awo_hybrid_session_v1', PREFKEY='awo_hybrid_pref_v1';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString(), fmt=t=>t?new Date(t).toLocaleString(): '—', tm=t=>t?new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';
const PERMS=['USERS','ADMINS','HELIPADS','ASSIGNMENTS','REFERENCES','BEARINGS','COLOUR_RULES','SCHEDULES','MESSAGES','CALIBRATION','HISTORY','AUDIT','EXPORT','ARCHIVE'];
const WX=['NIL','HZ','BR','FG','-DZ','DZ','+DZ','-RA','RA','+RA','-SN','SN','+SN','TS','SHRA','GR','GS'];
const HILL=['CCHT','CTHT','SOCC','NA'], HT=['HTV','HTPV','HTNV'];
let pref=JSON.parse(localStorage.getItem(PREFKEY)||'{"theme":"dark","lang":"en"}');document.documentElement.dataset.theme=pref.theme;
function seed(){let db=JSON.parse(localStorage.getItem(DBKEY)||'null');if(!db){let olddb=JSON.parse(localStorage.getItem('awo_v2_foundation_db')||'null');if(olddb){db={...olddb,observations:olddb.observations||[],images:olddb.images||[],sessions:olddb.captureSessions||olddb.sessions||[],tasks:olddb.tasks||[],airreps:olddb.airreps||[],messages:olddb.messages||[],requests:olddb.requests||[],peerRequests:olddb.peerRequests||[],profiles:olddb.profiles||[],audit:olddb.audit||[],deviceCal:olddb.deviceCal||{},settings:{airrepValidityMin:720,correctionWindowMin:10,aviatorCooldownMin:10,...(olddb.settings||{})},meta:{version:1,migratedFrom:'awo_v2_foundation_db'}};for(let h of Object.values(db.helipads||{})){h.name=h.name||h.id;h.mode=h.mode||'CAP_IN';h.weatherValidityMin=h.weatherValidityMin||h.weatherValidityMinutes||30;h.concurrentImageToleranceMin=h.concurrentImageToleranceMin||15;h.autoColour=h.autoColour==='OFF'?false:true;h.redVis=h.redVis||1000;h.yellowVis=h.yellowVis||3000;h.mixedLatched=!!h.mixedLatched;if(!Array.isArray(h.views)){let n=Number(h.views||4);h.views=Array.from({length:n},(_,i)=>({id:'V'+(i+1),label:'VIEW '+(i+1),bearing:(i*90)%360,tolerance:10,active:true,reference:null}))}}log(db,'SYSTEM','MIGRATE','Imported previous AWO V2 browser data');save(db)}else{db={users:{ARAOA:{id:'ARAOA',password:'00007',role:'ADMIN',observerType:null,helipads:[],active:true,primary:true,permissions:[...PERMS]}},helipads:{},observations:[],images:[],sessions:[],tasks:[],airreps:[],messages:[],requests:[],peerRequests:[],profiles:[],audit:[],deviceCal:{},settings:{airrepValidityMin:720,correctionWindowMin:10,aviatorCooldownMin:10},meta:{version:1}};log(db,'SYSTEM','INITIALIZE','AWO hybrid database created');save(db)}}return db}
let db=seed();
function normalizeDatabase(d){
  d=(d&&typeof d==='object')?d:{};
  d.users=(d.users&&typeof d.users==='object'&&!Array.isArray(d.users))?d.users:{};
  d.helipads=(d.helipads&&typeof d.helipads==='object'&&!Array.isArray(d.helipads))?d.helipads:{};
  for(const k of ['observations','images','sessions','tasks','airreps','messages','requests','peerRequests','profiles','audit']) if(!Array.isArray(d[k])) d[k]=[];
  d.deviceCal=(d.deviceCal&&typeof d.deviceCal==='object')?d.deviceCal:{};
  d.settings={airrepValidityMin:720,correctionWindowMin:10,aviatorCooldownMin:10,...(d.settings||{})};
  d.meta={version:4,...(d.meta||{})};
  for(const [id,u0] of Object.entries(d.users)){
    const u=(u0&&typeof u0==='object')?u0:{}; u.id=String(u.id||id).toUpperCase(); u.role=String(u.role||'AVIATOR').toUpperCase();
    u.observerType=u.role==='OBSERVER'&&u.observerType?String(u.observerType).toUpperCase():null; u.helipads=Array.isArray(u.helipads)?u.helipads.map(String):[]; u.permissions=Array.isArray(u.permissions)?u.permissions:[]; if(u.active===undefined)u.active=true; d.users[id]=u;
  }
  const a=d.users.ARAOA||{}; d.users.ARAOA={...a,id:'ARAOA',password:'00007',role:'ADMIN',observerType:null,active:true,primary:true,helipads:Array.isArray(a.helipads)?a.helipads:[],permissions:Array.isArray(a.permissions)&&a.permissions.length?a.permissions:[...PERMS]};
  for(const [id,h0] of Object.entries(d.helipads)){
    const h=(h0&&typeof h0==='object')?h0:{}; h.id=String(h.id||id); h.name=h.name||h.id; if(h.active===undefined)h.active=true; h.mode=h.mode==='OUTSTATION'?'OUTSTATION':'CAP_IN'; h.weatherValidityMin=Number(h.weatherValidityMin??h.weatherValidityMinutes??30)||30; h.concurrentImageToleranceMin=Number(h.concurrentImageToleranceMin??15)||15; h.autoColour=h.autoColour===false||h.autoColour==='OFF'?false:true; h.redVis=Number(h.redVis??1000)||1000; h.yellowVis=Number(h.yellowVis??3000)||3000; h.mixedLatched=!!h.mixedLatched;
    let v=h.views; if(!Array.isArray(v)){const n=Math.max(1,Math.min(6,Number(v)||4)); v=Array.from({length:n},(_,i)=>({id:'V'+(i+1),label:'VIEW '+(i+1),bearing:(i*90)%360,tolerance:10,active:true,reference:null}))}
    h.views=v.map((x,i)=>{x=(x&&typeof x==='object')?x:{}; return {...x,id:String(x.id||('V'+(i+1))),label:String(x.label||('VIEW '+(i+1))),bearing:((Number(x.bearing??(i*90))%360)+360)%360,tolerance:Math.max(0,Math.min(45,Number(x.tolerance??10)||0)),active:x.active!==false,reference:x.reference||null}}); d.helipads[id]=h;
  }
  return d;
}
db=normalizeDatabase(db);
function save(x=db){localStorage.setItem(DBKEY,JSON.stringify(x))}function log(d,actor,action,detail){d.audit.unshift({id:'AUD-'+Date.now()+Math.random(),time:now(),actor,action,detail});save(d)}
function session(){try{return JSON.parse(localStorage.getItem(SESSIONKEY)||'null')}catch{return null}}function currentUser(){let s=session();return s?db.users[s.id]:null}
function setSession(id){id?localStorage.setItem(SESSIONKEY,JSON.stringify({id})):localStorage.removeItem(SESSIONKEY)}
function toast(text,urgent=false){let d=document.createElement('div');d.className='toast';if(urgent)d.style.borderColor='var(--red)';d.textContent=text;$('toastHost').appendChild(d);setTimeout(()=>d.remove(),5000)}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]'))closeModal()});
function statusDot(s){return `<span class="dot ${s}"></span> ${s}`}
function dirFromBearing(b){if(b==null||!Number.isFinite(+b))return 'UNAVAILABLE';return ['N','NE','E','SE','S','SW','W','NW'][Math.round(((+b%360)+360)%360/45)%8]}
function angleDiff(target,current){return ((target-current+540)%360)-180}
function latestObservation(hel,src){return db.observations.filter(o=>o.helipadId===hel&&(!src||o.source===src)&&!o.superseded).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt))[0]||null}
function officialObservation(h){return latestObservation(h.id,h.mode==='OUTSTATION'?'OUT':'IN')}
function latestImages(hel){let a=db.images.filter(i=>i.helipadId===hel).sort((a,b)=>new Date(b.capturedAt)-new Date(a.capturedAt)),m={};a.forEach(i=>{if(!m[i.viewId])m[i.viewId]=i});return Object.values(m)}
function imageStatus(h){let imgs=latestImages(h.id);if(!imgs.length)return 'NO IMAGE';if(h.mixedLatched)return 'MIXED';let ss=new Set(imgs.map(i=>i.sessionId));if(ss.size>1)return 'MIXED';return imgs[0].source==='OUT'?'OUT':'CAP'}
function calcColour(h,o){if(h.autoColour===false)return o.observerColour||'GREEN';let v=+o.visibility,wx=o.weatherCodes||[];if(v<(h.redVis??1000)||o.htStatus==='HTNV'||wx.some(x=>['+RA','+SN','TS','GR','GS'].includes(x)))return 'RED';if(v<(h.yellowVis??3000)||o.htStatus==='HTPV'||wx.some(x=>['RA','SN','FG','BR','SHRA'].includes(x)))return 'YELLOW';return 'GREEN'}
function statusFor(h){let o=officialObservation(h),imgs=latestImages(h.id);if(!o)return {status:imgs.length?'PURPLE':'GREY',obs:null};let age=(Date.now()-new Date(o.observedAt))/60000;if(age<=(h.weatherValidityMin??30))return {status:o.systemColour||o.observerColour||'GREEN',obs:o};let newer=imgs.some(i=>new Date(i.capturedAt)>new Date(o.observedAt));return {status:newer?'PURPLE':'GREY',obs:o}}
function navFor(u){if(u.role==='ADMIN')return [['dashboard','⌂ Dashboard'],['helipads','◎ Helipads'],['users','◉ Users / Personnel'],['assign','⇄ Assignments'],['references','▣ Reference Images'],['rules','◫ Rules & Radials'],['schedules','◷ Schedules'],['airrepAdmin','✈ AIRREP'],['messages','⚠ Alerts / Messages'],['audit','▤ Audit / Reports'],['settings','⚙ Settings']];if(u.role==='CAPTURER')return [['capHome','⌂ Capture Home'],['capHistory','▣ Image History'],['capTasks','◷ Tasks']];if(u.role==='OBSERVER'&&u.observerType==='INSTATION')return [['inHome','⌂ Dashboard'],['inEntry','☁ Weather Entry'],['inImages','▣ Images'],['inHistory','◷ History'],['inAlerts','⚠ Alerts']];if(u.role==='OBSERVER')return [['outHome','⌂ Dashboard'],['outEntry','☁ Weather + METAR'],['outCamera','▣ Required Views'],['outHistory','◷ History'],['outAlerts','⚠ Alerts']];return [['avHome','⌂ Latest Weather'],['avAirrep','✈ AIRREP'],['avCompare','⇆ Compare'],['avAlerts','⚠ Alerts'],['avPeer','⇄ Pilot-to-Pilot'],['avHistory','◷ History']];}
let currentPage=null;function renderNav(page){let u=currentUser(),nav=navFor(u),side=$('sidebar');side.innerHTML=nav.map(([id,l])=>`<button class="navBtn ${id===page?'active':''}" data-page="${id}">${l}</button>`).join('');side.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page))}
function showPage(page){currentPage=page;renderNav(page);let fn=pages[page]||pages.dashboard;try{let html=fn();$('content').innerHTML=html||`<div class="card"><div class="cardBody">No content available.</div></div>`;bindPage(page)}catch(error){console.error('AWO page render error',page,error);$('content').innerHTML=`<div class="card errorCard"><div class="cardHead"><b>PAGE COULD NOT LOAD</b></div><div class="cardBody"><p>The application has not frozen. This page hit a data/render error.</p><div class="note"><b>Page:</b> ${esc(page)}<br><b>Error:</b> ${esc(error&&error.message?error.message:String(error))}</div><button class="btn primary" id="recoverDashboard">RETURN TO HOME</button></div></div>`;let r=$('recoverDashboard');if(r)r.onclick=()=>showPage(navFor(currentUser())[0][0])}if(window.matchMedia('(max-width:900px)').matches)requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))}
function login(){let id=$('loginId').value.trim().toUpperCase(),p=$('loginPass').value,u=db.users[id];if(!u||!u.active||u.password!==p){$('loginMsg').textContent='Invalid ID/password or inactive account.';return}setSession(id);log(db,id,'LOGIN','User logged in');route()}
function logout(){let u=currentUser();if(u)log(db,u.id,'LOGOUT','User logged out');setSession(null);route()}
function route(){let u=currentUser();$('loginPage').classList.toggle('hidden',!!u);$('shell').classList.toggle('hidden',!u);$('topbar').classList.toggle('hidden',!u);if(!u)return;$('sessionLine').textContent=`${u.id} • ${u.role}${u.observerType?' / '+u.observerType:''}`;let first=navFor(u)[0][0];showPage(first);refreshNotifications()}
$('loginBtn').onclick=login;$('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=logout;$('themeBtn').onclick=()=>{pref.theme=pref.theme==='dark'?'light':'dark';localStorage.setItem(PREFKEY,JSON.stringify(pref));document.documentElement.dataset.theme=pref.theme};$('langBtn').onclick=()=>{pref.lang=pref.lang==='en'?'hi':'en';localStorage.setItem(PREFKEY,JSON.stringify(pref));toast(pref.lang==='hi'?'हिन्दी मोड चयनित — operational codes unchanged':'English mode selected')};

function pageTitle(t,actions=''){return `<div class="pageTitle"><h2>${t}</h2><div class="row">${actions}</div></div>`}
function kpis(){let hs=Object.values(db.helipads).filter(h=>h.active),us=Object.values(db.users).filter(u=>u.active);let st=hs.map(h=>statusFor(h).status);return `<div class="grid g4"><div class="kpi"><small>TOTAL HELIPADS</small><strong>${hs.length}</strong></div><div class="kpi"><small>ACTIVE USERS</small><strong>${us.length}</strong></div><div class="kpi"><small>RED / PURPLE</small><strong>${st.filter(x=>x==='RED'||x==='PURPLE').length}</strong></div><div class="kpi"><small>PENDING TASKS</small><strong>${db.tasks.filter(t=>!['COMPLETE','CANCELLED'].includes(t.status)).length}</strong></div></div>`}
function dashboard(){let hs=Object.values(db.helipads).filter(h=>h.active);return pageTitle('ADMINISTRATOR — COMMAND CENTER')+kpis()+`<div class="grid g2" style="margin-top:12px"><div class="card"><div class="cardHead"><b>HELIPAD STATUS</b></div><div class="cardBody"><div class="helipadCards">${hs.map(h=>{let s=statusFor(h);return `<div class="helipadCard" data-open-hel="${h.id}"><b>${esc(h.name)}</b><div>${statusDot(s.status)}</div><small>${s.obs?`VIS ${s.obs.visibility} m • ${(s.obs.weatherCodes||[]).join(' ')}`:'NO WEATHER'} • 📷 ${imageStatus(h)}</small></div>`}).join('')||'No helipads created.'}</div></div></div><div class="card"><div class="cardHead"><b>LATEST ALERTS / REQUESTS</b></div><div class="cardBody">${latestAlertsHtml()}</div></div></div>`}
function helipads(){return pageTitle('HELIPAD MANAGEMENT','<button class="btn primary" id="addHel">+ ADD HELIPAD</button>')+`<div class="card"><div class="cardBody"><div class="toolbar"><input id="helSearch" placeholder="Search helipad"><select id="helStatus"><option>ALL</option><option>ACTIVE</option><option>ARCHIVED</option></select></div><div class="tableWrap" style="margin-top:10px"><table><thead><tr><th>HELIPAD</th><th>MODE</th><th>VALIDITY</th><th>COLOUR</th><th>IMAGES</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody id="helRows"></tbody></table></div></div></div>`}
function users(){return pageTitle('USERS / PERSONNEL','<button class="btn primary" id="addUser">+ ADD USER</button>')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>SEARCH PERSONNEL</b></div><div class="cardBody"><input id="userSearch" placeholder="Search ID / role"><div id="userList" class="personList" style="margin-top:10px"></div></div></div><div class="card"><div class="cardHead"><b>SELECTED USER</b></div><div id="userDetail" class="cardBody">Select a user to manage profile and helipad access.</div></div></div>`}
function assignments(){return pageTitle('FAST HELIPAD ASSIGNMENT')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>BY PERSON</b></div><div class="cardBody"><select id="assignUser">${Object.values(db.users).filter(u=>u.active&&u.role!=='ADMIN').map(u=>`<option value="${u.id}">${u.id} — ${u.role}${u.observerType?' / '+u.observerType:''}</option>`).join('')}</select><div id="assignByUser" class="assignGrid" style="margin-top:10px"></div><button class="btn success full" id="saveAssignUser" style="margin-top:10px">SAVE CHANGES</button></div></div><div class="card"><div class="cardHead"><b>BY HELIPAD</b></div><div class="cardBody"><select id="assignHel">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<option>${h.id}</option>`).join('')}</select><div id="assignByHel" class="assignGrid" style="margin-top:10px"></div><button class="btn success full" id="saveAssignHel" style="margin-top:10px">SAVE CHANGES</button></div></div></div>`}
function references(){return pageTitle('REFERENCE IMAGES')+`<div class="card"><div class="cardBody"><div class="toolbar"><select id="refHel">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<option>${h.id}</option>`).join('')}</select><button class="btn" id="refreshRef">REFRESH</button></div><div id="refGrid" class="imgGrid" style="margin-top:10px"></div></div></div>`}
function rules(){return pageTitle('RULES, RADIALS & COLOUR LOGIC')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>HELIPAD RULES</b></div><div class="cardBody"><select id="ruleHel">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<option>${h.id}</option>`).join('')}</select><div id="ruleForm"></div></div></div><div class="card"><div class="cardHead"><b>CAPTURE VIEWS / RADIALS</b></div><div id="viewRules" class="cardBody"></div></div></div>`}
function schedules(){return pageTitle('SCHEDULES / REMINDERS')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>CREATE TASK</b></div><div class="cardBody"><label>Helipad</label><select id="taskHel">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<option>${h.id}</option>`).join('')}</select><label>Type</label><select id="taskType"><option>IMAGE</option><option>WEATHER</option><option>NEW_OBSERVATION</option></select><label>Due</label><input id="taskDue" type="datetime-local"><button class="btn primary full" id="createTask" style="margin-top:10px">CREATE TASK</button><small>Reminder is automatically 10 minutes before due time.</small></div></div><div class="card"><div class="cardHead"><b>ACTIVE TASKS</b></div><div id="taskList" class="cardBody"></div></div></div>`}
function airrepAdmin(){return pageTitle('AIRREP MANAGEMENT')+airrepTable(true)}
function messages(){return pageTitle('ALERTS / ADMIN MESSAGES')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>SEND MESSAGE</b></div><div class="cardBody"><label>Priority</label><select id="msgPriority"><option>INFO</option><option>IMPORTANT</option><option>URGENT</option></select><label>Recipient scope</label><select id="msgScope"><option value="ALL">ALL USERS</option><option value="AVIATOR">AVIATORS</option><option value="OBSERVER">OBSERVERS</option><option value="CAPTURER">CAPTURERS</option></select><label>Message</label><textarea id="msgText"></textarea><label>Expiry</label><input id="msgExpiry" type="datetime-local"><button class="btn primary full" id="sendMsg" style="margin-top:10px">SEND</button></div></div><div class="card"><div class="cardHead"><b>ACTIVE MESSAGES</b></div><div class="cardBody">${activeMessagesHtml()}</div></div></div>`}
function audit(){return pageTitle('AUDIT / REPORTS','<button class="btn" id="exportAudit">EXPORT EXCEL-COMPATIBLE</button><button class="btn" id="printReport">PRINT / SAVE PDF</button>')+`<div class="card"><div class="cardBody"><div class="toolbar"><input id="auditSearch" placeholder="Filter user / action / helipad"></div><div class="tableWrap" style="margin-top:10px"><table><thead><tr><th>TIME</th><th>ACTOR</th><th>ACTION</th><th>DETAIL</th></tr></thead><tbody id="auditRows"></tbody></table></div></div></div>`}
function settings(){return pageTitle('SYSTEM SETTINGS')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>GENERAL</b></div><div class="cardBody"><label>AIRREP validity (minutes)</label><input id="airrepVal" type="number" value="${db.settings.airrepValidityMin}"><label>Observer correction window (minutes)</label><input id="corrWin" type="number" value="${db.settings.correctionWindowMin}"><label>Aviator image request cooldown (minutes)</label><input id="cooldown" type="number" value="${db.settings.aviatorCooldownMin}"><button class="btn success full" id="saveSettings" style="margin-top:10px">SAVE CHANGES</button></div></div><div class="card"><div class="cardHead"><b>DATA / OFFLINE</b></div><div class="cardBody"><button class="btn full" id="backupData">EXPORT BACKUP JSON</button><label>Restore backup</label><input id="restoreFile" type="file" accept="application/json"><button class="btn warn full" id="restoreBtn">RESTORE</button><div class="note">No GPS/location data is collected. Browser-local prototype syncs when a real backend is connected later.</div><hr><h3>DEVICE PRESSURE CALIBRATION</h3><label>Device / User key</label><input id="calKey" placeholder="e.g. CAP001-PHONE-A"><label>Pressure offset hPa</label><input id="calOffset" type="number" step="0.1"><button class="btn" id="saveCal">SAVE CALIBRATION</button><hr><h3>PRIMARY ADMINISTRATOR TRANSFER</h3><select id="primaryTo">${Object.values(db.users).filter(u=>u.role==='ADMIN'&&!u.primary&&u.active).map(u=>`<option>${u.id}</option>`).join('')}</select><label>Current Primary password</label><input id="primaryPass" type="password"><button class="btn danger full" id="transferPrimary">TRANSFER PRIMARY ADMINISTRATOR</button></div></div></div>`}

function capHome(){let u=currentUser(),h=db.helipads[(u.helipads||[])[0]];if(!h)return pageTitle('CAPTURER')+'<div class="note">No helipad assigned.</div>';return pageTitle('CAPTURER — CAMERA-FIRST WORKFLOW')+`<div class="card"><div class="cardHead"><b>${esc(h.name)}</b><span>📷 ${imageStatus(h)}</span></div><div class="cardBody"><div class="imgGrid">${h.views.map(v=>`<div class="imgCard"><b>${esc(v.label)}</b><div>Target ${v.bearing}° ${dirFromBearing(v.bearing)} ±${v.tolerance}°</div>${v.reference?`<img src="${v.reference}">`:'<div class="note">No reference image</div>'}<button class="btn primary full" data-capture-view="${v.id}" style="margin-top:8px">OPEN CAMERA</button></div>`).join('')}</div></div></div>`}
function capHistory(){let u=currentUser(),ids=u.helipads||[],a=db.images.filter(i=>ids.includes(i.helipadId)&&i.capturedBy===u.id).sort((a,b)=>new Date(b.capturedAt)-new Date(a.capturedAt));return pageTitle('IMAGE HISTORY')+`<div class="imgGrid">${a.slice(0,30).map(imageCardHtml).join('')||'No captures yet.'}</div>`}
function capTasks(){let u=currentUser();return pageTitle('TASKS')+taskHtml(db.tasks.filter(t=>t.assignedUserId===u.id||u.helipads.includes(t.helipadId)))}

function inHome(){let u=currentUser(),hs=(u.helipads||[]).map(id=>db.helipads[id]).filter(Boolean);let updates=db.observations.filter(o=>u.helipads.includes(o.helipadId)).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt)).slice(0,10);return pageTitle('INSTATION OBSERVER — DASHBOARD')+`<div class="card"><div class="cardHead"><b>ASSIGNED HELIPADS</b></div><div class="cardBody"><div class="helipadCards">${hs.map(h=>{let s=statusFor(h);return `<div class="helipadCard" data-in-hel="${h.id}"><b>${h.name}</b><div>${statusDot(s.status)}</div><small>${s.obs?`VIS ${s.obs.visibility} m • ${(s.obs.weatherCodes||[]).join(' ')}`:'NO WEATHER'}</small></div>`}).join('')}</div></div></div><div class="card" style="margin-top:12px"><div class="cardHead"><b>LATEST UPDATES</b></div><div class="cardBody">${updates.map(o=>`<div class="timelineItem"><b>${o.helipadId} • ${o.systemColour}</b> — ${fmt(o.observedAt)}<br><small>VIS ${o.visibility} • ${(o.weatherCodes||[]).join(' ')} • ${o.hillTop} • ${o.htStatus}</small></div>`).join('')||'No updates.'}</div></div>`}
function inEntry(){let u=currentUser();return pageTitle('INSTATION — WEATHER ENTRY')+`<div class="card"><div class="cardBody"><label>Helipad</label><select id="inHel">${u.helipads.map(id=>`<option>${id}</option>`).join('')}</select><div id="inEntryVisuals" style="margin-top:10px"></div><div id="inForm"></div></div></div>`}
function inImages(){let u=currentUser();return pageTitle('REFERENCE & LATEST IMAGES')+`<div class="card"><div class="cardBody"><label>Helipad</label><select id="inImgHel">${u.helipads.map(id=>`<option>${id}</option>`).join('')}</select><div id="inImagesBox"></div></div></div>`}
function inHistory(){return observerHistory('IN')}
function inAlerts(){return pageTitle('ALERTS')+`<div class="card"><div class="cardBody">${latestAlertsHtml()}</div></div>`}

function outHome(){let u=currentUser(),h=db.helipads[u.helipads[0]];if(!h)return pageTitle('OUTSTATION OBSERVER')+'<div class="note">No helipad assigned.</div>';let s=statusFor(h);return pageTitle('OUTSTATION OBSERVER — '+esc(h.name))+`<div class="grid g3"><div class="kpi"><small>CURRENT STATUS</small><strong>${s.status}</strong></div><div class="kpi"><small>IMAGE STATUS</small><strong>${imageStatus(h)}</strong></div><div class="kpi"><small>WEATHER VALIDITY</small><strong>${s.obs?Math.max(0,Math.round((h.weatherValidityMin-(Date.now()-new Date(s.obs.observedAt))/60000)))+'m':'—'}</strong></div></div><div class="row" style="margin-top:12px"><button class="btn primary" data-page="outEntry">ENTER / UPDATE WEATHER</button><button class="btn purple" data-page="outCamera">REQUIRED VIEWS / CAMERA</button></div>`}
function outEntry(){let u=currentUser(),id=u.helipads[0];return pageTitle('OUTSTATION — WEATHER + METAR')+`<div class="card"><div class="cardBody"><div id="outForm" data-hel="${id}"></div></div></div>`}
function outCamera(){let u=currentUser(),h=db.helipads[u.helipads[0]];return pageTitle('OUTSTATION — REQUIRED VIEWS')+`<div class="card"><div class="cardBody"><div class="imgGrid">${h.views.map(v=>`<div class="imgCard"><b>${v.label}</b><div>Target ${v.bearing}° ${dirFromBearing(v.bearing)} ±${v.tolerance}°</div>${v.reference?`<img src="${v.reference}">`:'<div class="note">No reference image</div>'}<button class="btn primary full" data-capture-view="${v.id}" style="margin-top:8px">OPEN CAMERA</button></div>`).join('')}</div></div></div>`}
function outHistory(){return observerHistory('OUT')}
function outAlerts(){return pageTitle('ALERTS')+`<div class="card"><div class="cardBody">${latestAlertsHtml()}</div></div>`}

function avHome(){let u=currentUser();return pageTitle('AVIATOR — LATEST HELIPAD WEATHER','<button class="btn" id="manageAvHel">ADD / REMOVE DISPLAYED</button>')+`<div class="card"><div class="cardBody"><div class="toolbar"><input id="avSearch" placeholder="Search helipad"><select id="avFilter"><option>ALL</option><option>GREEN</option><option>YELLOW</option><option>RED</option><option>PURPLE</option><option>GREY</option></select></div><div class="tableWrap" style="margin-top:10px"><table><thead><tr><th>HELIPAD</th><th>VIS</th><th>WEATHER</th><th>HILL TOP</th><th>HT STATUS</th><th>AC/ANC</th><th>STATUS</th><th>SOURCE</th><th>IMAGE</th><th>UPDATED</th></tr></thead><tbody id="avRows"></tbody></table></div></div></div>`}
function avAirrep(){let u=currentUser();return pageTitle('AIRREP — PILOT REPORT')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>NEW AIRREP</b></div><div class="cardBody"><label>From</label><select id="arFrom">${u.helipads.map(id=>`<option>${id}</option>`).join('')}</select><label>To</label><select id="arTo">${u.helipads.map(id=>`<option>${id}</option>`).join('')}</select><label>Enroute remarks</label><textarea id="arRemarks"></textarea><div class="grid g2"><div><h4>FROM HELIPAD</h4><label>Temperature °C</label><input id="arT1" type="number"><label>Pressure type</label><select id="arPType1"><option>QFE</option><option>QNH</option><option>QFF</option></select><label>Pressure hPa</label><input id="arP1" type="number"></div><div><h4>TO HELIPAD</h4><label>Temperature °C</label><input id="arT2" type="number"><label>Pressure type</label><select id="arPType2"><option>QFE</option><option>QNH</option><option>QFF</option></select><label>Pressure hPa</label><input id="arP2" type="number"></div></div><button class="btn success full" id="submitAirrep">SUBMIT AIRREP</button></div></div><div class="card"><div class="cardHead"><b>RECENT AIRREPS</b></div><div class="cardBody">${airrepCards()}</div></div></div>`}
function avCompare(){let u=currentUser();return pageTitle('COMPARE HELIPADS')+`<div class="card"><div class="cardBody"><div class="assignGrid" id="comparePick">${u.helipads.map(id=>`<button class="chip" data-compare="${id}">${id}</button>`).join('')}</div><div class="row" style="margin-top:10px"><button class="btn primary" id="doCompare">COMPARE SELECTED</button><label style="margin:0"><input type="checkbox" id="compareImages" style="width:auto;min-height:auto"> SHOW IMAGES</label></div><div id="compareResult" style="margin-top:10px"></div></div></div>`}
function avAlerts(){return pageTitle('AVIATOR ALERTS / PROFILES')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>PER-HELIPAD NOTIFICATIONS</b></div><div id="avAlertList" class="cardBody"></div></div><div class="card"><div class="cardHead"><b>PERSONAL ALERT PROFILES</b></div><div class="cardBody"><input id="profileName" placeholder="Profile name"><button class="btn primary full" id="saveProfile" style="margin-top:8px">SAVE CURRENT ALERTS AS PROFILE</button><div id="profileList" style="margin-top:10px"></div></div></div></div>`}
function avPeer(){let u=currentUser(),others=Object.values(db.users).filter(x=>x.active&&x.role==='AVIATOR'&&x.id!==u.id&&x.helipads.some(h=>u.helipads.includes(h)));return pageTitle('PILOT-TO-PILOT — NOTIFICATION & ACCEPTANCE')+`<div class="grid g2"><div class="card"><div class="cardHead"><b>SEND</b></div><div class="cardBody"><label>Recipient</label><select id="peerTo">${others.map(x=>`<option>${x.id}</option>`).join('')}</select><label>Helipad</label><select id="peerHel">${u.helipads.map(id=>`<option>${id}</option>`).join('')}</select><label>Information</label><select id="peerType"><option>LATEST IMAGE + WEATHER</option><option>AIRREP</option><option>WEATHER ONLY</option></select><label>Optional message</label><textarea id="peerMsg"></textarea><button class="btn primary full" id="sendPeer">SEND REQUEST</button></div></div><div class="card"><div class="cardHead"><b>INCOMING / HISTORY</b></div><div id="peerList" class="cardBody"></div></div></div>`}
function avHistory(){let u=currentUser();let obs=db.observations.filter(o=>u.helipads.includes(o.helipadId)).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt));return pageTitle('AVIATOR HISTORY')+`<div class="card"><div class="cardBody">${obs.slice(0,30).map(o=>`<div class="timelineItem"><b>${o.helipadId} • ${o.systemColour}</b> — ${fmt(o.observedAt)}<br><small>VIS ${o.visibility} • ${(o.weatherCodes||[]).join(' ')} • ${o.hillTop} • ${o.htStatus}</small></div>`).join('')||'No history.'}</div></div>`}

const pages={dashboard,helipads,users,assign:assignments,references,rules,schedules,airrepAdmin,messages,audit,settings,capHome,capHistory,capTasks,inHome,inEntry,inImages,inHistory,inAlerts,outHome,outEntry,outCamera,outHistory,outAlerts,avHome,avAirrep,avCompare,avAlerts,avPeer,avHistory};

function bindPage(p){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-open-hel]').forEach(x=>x.onclick=()=>helipadDetail(x.dataset.openHel));document.querySelectorAll('[data-capture-view]').forEach(x=>x.onclick=()=>openCameraFor(x.dataset.captureView));if(p==='helipads')bindHelipads();if(p==='users')bindUsers();if(p==='assign')bindAssignments();if(p==='references')bindReferences();if(p==='rules')bindRules();if(p==='schedules')bindSchedules();if(p==='messages')bindMessages();if(p==='audit')bindAudit();if(p==='settings')bindSettings();if(p==='inEntry')bindInEntry();if(p==='inHome')document.querySelectorAll('[data-in-hel]').forEach(x=>x.onclick=()=>{showPage('inEntry');setTimeout(()=>{$('inHel').value=x.dataset.inHel;renderWeatherForm('inForm',x.dataset.inHel,'IN')},0)});if(p==='inImages')bindInImages();if(p==='outEntry')renderWeatherForm('outForm',currentUser().helipads[0],'OUT');if(p==='avHome')bindAvHome();if(p==='avAirrep')bindAirrep();if(p==='avCompare')bindCompare();if(p==='avAlerts')bindAvAlerts();if(p==='avPeer')bindPeer();}

function helipadDefault(id,name,mode){return {id,name,mode,active:true,weatherValidityMin:30,concurrentImageToleranceMin:15,autoColour:true,redVis:1000,yellowVis:3000,mixedLatched:false,views:[0,90,180,270].map((b,i)=>({id:'V'+(i+1),label:'VIEW '+(i+1),bearing:b,tolerance:10,active:true,reference:null}))}}
function bindHelipads(){let render=()=>{let q=$('helSearch').value.toUpperCase(),st=$('helStatus').value;$('helRows').innerHTML=Object.values(db.helipads).filter(h=>h.name.toUpperCase().includes(q)&&(st==='ALL'||(st==='ACTIVE'?h.active:!h.active))).map(h=>{let s=statusFor(h);return `<tr><td>${h.name}</td><td>${h.mode}</td><td>${h.weatherValidityMin}m</td><td>${h.autoColour?'AUTO':'OBSERVER'}</td><td>${imageStatus(h)}</td><td class="status-${s.status}">${s.status}</td><td><button class="btn" data-edit-hel="${h.id}">EDIT</button> <button class="btn" data-toggle-hel="${h.id}">${h.active?'ARCHIVE':'RESTORE'}</button></td></tr>`}).join('');document.querySelectorAll('[data-edit-hel]').forEach(b=>b.onclick=()=>editHelipad(b.dataset.editHel));document.querySelectorAll('[data-toggle-hel]').forEach(b=>b.onclick=()=>{let h=db.helipads[b.dataset.toggleHel];h.active=!h.active;log(db,currentUser().id,h.active?'RESTORE_HELIPAD':'ARCHIVE_HELIPAD',h.id);save();render()})};$('helSearch').oninput=render;$('helStatus').onchange=render;$('addHel').onclick=()=>editHelipad(null);render()}
function editHelipad(id){let h=id?db.helipads[id]:helipadDefault('','','CAP_IN');openModal(id?'EDIT HELIPAD':'ADD HELIPAD',`<div class="grid g2"><div><label>ID</label><input id="eHid" value="${esc(h.id)}" ${id?'disabled':''}><label>Name</label><input id="eHname" value="${esc(h.name)}"><label>Mode</label><select id="eHmode"><option value="CAP_IN" ${h.mode==='CAP_IN'?'selected':''}>Capturer + Instation</option><option value="OUTSTATION" ${h.mode==='OUTSTATION'?'selected':''}>Outstation Observer</option></select></div><div><label>Weather validity min</label><input id="eHval" type="number" value="${h.weatherValidityMin}"><label>Concurrent image tolerance min</label><input id="eHimgtol" type="number" value="${h.concurrentImageToleranceMin}"><label>Automatic colour</label><select id="eHauto"><option value="1" ${h.autoColour?'selected':''}>ON</option><option value="0" ${!h.autoColour?'selected':''}>OFF</option></select></div></div><button class="btn success full" id="saveHelModal">SAVE HELIPAD</button>`);$('saveHelModal').onclick=()=>{let hid=$('eHid').value.trim().toUpperCase(),name=$('eHname').value.trim().toUpperCase();if(!hid||!name)return toast('ID and name required');let obj=id?h:helipadDefault(hid,name,$('eHmode').value);obj.id=hid;obj.name=name;obj.mode=$('eHmode').value;obj.weatherValidityMin=+$('eHval').value||30;obj.concurrentImageToleranceMin=+$('eHimgtol').value||15;obj.autoColour=$('eHauto').value==='1';db.helipads[hid]=obj;log(db,currentUser().id,id?'UPDATE_HELIPAD':'CREATE_HELIPAD',hid);save();closeModal();showPage('helipads')}}
function helipadDetail(id){let h=db.helipads[id],s=statusFor(h);openModal(h.name,`<div class="grid g2"><div><h3>${statusDot(s.status)}</h3><p>Mode: ${h.mode}</p><p>Validity: ${h.weatherValidityMin} min</p><p>Image: ${imageStatus(h)}</p></div><div><h3>Latest weather</h3>${s.obs?`VIS ${s.obs.visibility}m<br>${(s.obs.weatherCodes||[]).join(' ')}<br>${s.obs.hillTop} • ${s.obs.htStatus}`:'No weather'}</div></div><h3>Latest images</h3><div class="imgGrid">${latestImages(id).map(imageCardHtml).join('')||'No images'}</div>`)}

let selectedUserId=null;function bindUsers(){let renderList=()=>{let q=$('userSearch').value.toUpperCase();let arr=Object.values(db.users).filter(u=>u.id.includes(q)||u.role.includes(q)||(u.observerType||'').includes(q));$('userList').innerHTML=arr.map(u=>`<div class="personItem ${u.id===selectedUserId?'active':''}" data-user="${u.id}"><b>${u.id}</b><br><small>${u.role}${u.observerType?' / '+u.observerType:''} • ${(u.helipads||[]).length} helipad(s)</small></div>`).join('');document.querySelectorAll('[data-user]').forEach(x=>x.onclick=()=>{selectedUserId=x.dataset.user;renderList();renderUserDetail()})};$('userSearch').oninput=renderList;$('addUser').onclick=()=>userEditor();renderList()}
function renderUserDetail(){let u=db.users[selectedUserId];$('userDetail').innerHTML=`<h3>${u.id}</h3><p>${u.role}${u.observerType?' / '+u.observerType:''} • ${u.active?'ACTIVE':'INACTIVE'}</p><div class="assignGrid">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<button class="chip ${(u.helipads||[]).includes(h.id)?'on':''}" data-userhel="${h.id}">${h.id}</button>`).join('')}</div><div class="row" style="margin-top:10px"><button class="btn success" id="saveUserHel">SAVE HELIPADS</button><button class="btn" id="editUser">EDIT USER</button></div>`;document.querySelectorAll('[data-userhel]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('saveUserHel').onclick=()=>{let ids=[...document.querySelectorAll('[data-userhel].on')].map(x=>x.dataset.userhel);if(!validateAssignments(u,ids))return;u.helipads=ids;log(db,currentUser().id,'CHANGE_ASSIGNMENTS',`${u.id}: ${ids.join(',')}`);save();toast('Assignments saved')};$('editUser').onclick=()=>userEditor(u.id)}
function validateAssignments(u,ids){if(u.role==='CAPTURER'&&ids.length!==1){toast('Capturer must have exactly one helipad');return false}if(u.role==='OBSERVER'&&u.observerType==='OUTSTATION'&&ids.length!==1){toast('Outstation Observer must have exactly one helipad');return false}return true}
function userEditor(id){let u=id?db.users[id]:{id:'',password:'',role:'CAPTURER',observerType:null,active:true,primary:false,permissions:[]};openModal(id?'EDIT USER':'ADD USER',`<div class="grid g2"><div><label>User ID</label><input id="euId" value="${u.id}" ${id?'disabled':''}><label>Password</label><input id="euPass" value="${u.password||''}"><label>Role</label><select id="euRole"><option ${u.role==='CAPTURER'?'selected':''}>CAPTURER</option><option ${u.role==='OBSERVER'?'selected':''}>OBSERVER</option><option ${u.role==='AVIATOR'?'selected':''}>AVIATOR</option><option ${u.role==='ADMIN'?'selected':''}>ADMIN</option></select><label>Observer type</label><select id="euObs"><option value="">—</option><option value="INSTATION" ${u.observerType==='INSTATION'?'selected':''}>INSTATION</option><option value="OUTSTATION" ${u.observerType==='OUTSTATION'?'selected':''}>OUTSTATION</option></select></div><div><label>Helipads</label><div class="assignGrid">${Object.values(db.helipads).filter(h=>h.active).map(h=>`<button class="chip ${(u.helipads||[]).includes(h.id)?'on':''}" data-euhel="${h.id}">${h.id}</button>`).join('')}</div><label>Active</label><select id="euActive"><option value="1" ${u.active?'selected':''}>YES</option><option value="0" ${!u.active?'selected':''}>NO</option></select></div></div><div id="adminPermBox" class="${u.role==='ADMIN'?'':'hidden'}"><label>Administrator permissions — individual switches</label><div class="assignGrid">${PERMS.map(p=>`<button class="chip ${(u.permissions||[]).includes(p)?'on':''}" data-perm="${p}">${p}</button>`).join('')}</div></div><button class="btn success full" id="saveUserModal">SAVE USER</button>`);document.querySelectorAll('[data-euhel]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));document.querySelectorAll('[data-perm]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('euRole').onchange=()=>$('adminPermBox').classList.toggle('hidden',$('euRole').value!=='ADMIN');$('saveUserModal').onclick=()=>{let uid=$('euId').value.trim().toUpperCase(),role=$('euRole').value,obs=$('euObs').value||null,ids=[...document.querySelectorAll('[data-euhel].on')].map(x=>x.dataset.euhel),obj=id?u:{id:uid,primary:false,permissions:[],helipads:[]};obj.password=$('euPass').value;obj.role=role;obj.observerType=role==='OBSERVER'?obs:null;let newActive=$('euActive').value==='1';if(obj.primary&&!newActive)return toast('Primary Administrator cannot be deactivated');obj.active=newActive;if(!validateAssignments(obj,ids))return;obj.helipads=ids;if(role==='ADMIN'){let creator=currentUser(),allowed=new Set(creator.permissions||[]);obj.permissions=[...document.querySelectorAll('[data-perm].on')].map(x=>x.dataset.perm).filter(x=>allowed.has(x)||creator.primary)}else obj.permissions=[];db.users[uid]=obj;log(db,currentUser().id,id?'UPDATE_USER':'CREATE_USER',uid);save();closeModal();showPage('users')}}

let stagedUserAssign=[],stagedHelAssign=[];function bindAssignments(){let loadUser=()=>{let u=db.users[$('assignUser').value];stagedUserAssign=[...(u.helipads||[])];$('assignByUser').innerHTML=Object.values(db.helipads).filter(h=>h.active).map(h=>`<button class="chip ${stagedUserAssign.includes(h.id)?'on':''}" data-abu="${h.id}">${h.id}</button>`).join('');document.querySelectorAll('[data-abu]').forEach(b=>b.onclick=()=>{b.classList.toggle('on');stagedUserAssign=[...document.querySelectorAll('[data-abu].on')].map(x=>x.dataset.abu)})};let loadHel=()=>{let id=$('assignHel').value;stagedHelAssign=Object.values(db.users).filter(u=>(u.helipads||[]).includes(id)).map(u=>u.id);$('assignByHel').innerHTML=Object.values(db.users).filter(u=>u.active&&u.role!=='ADMIN').map(u=>`<button class="chip ${stagedHelAssign.includes(u.id)?'on':''}" data-abh="${u.id}">${u.id}</button>`).join('');document.querySelectorAll('[data-abh]').forEach(b=>b.onclick=()=>b.classList.toggle('on'))};$('assignUser').onchange=loadUser;$('assignHel').onchange=loadHel;$('saveAssignUser').onclick=()=>{let u=db.users[$('assignUser').value],ids=[...document.querySelectorAll('[data-abu].on')].map(x=>x.dataset.abu);if(!validateAssignments(u,ids))return;u.helipads=ids;log(db,currentUser().id,'CHANGE_ASSIGNMENTS',`${u.id}: ${ids.join(',')}`);save();toast('Saved')};$('saveAssignHel').onclick=()=>{let hel=$('assignHel').value,selected=[...document.querySelectorAll('[data-abh].on')].map(x=>x.dataset.abh);for(let u of Object.values(db.users)){if(u.role==='ADMIN')continue;let next=(u.helipads||[]).filter(x=>x!==hel);if(selected.includes(u.id))next.push(hel);if(validateAssignments(u,next))u.helipads=[...new Set(next)]}log(db,currentUser().id,'CHANGE_ASSIGNMENTS_BY_HELIPAD',hel);save();toast('Saved')};loadUser();loadHel()}

function bindReferences(){let render=()=>{let h=db.helipads[$('refHel').value];$('refGrid').innerHTML=h.views.map(v=>`<div class="imgCard"><b>${v.label}</b><div>${v.bearing}° ${dirFromBearing(v.bearing)} ±${v.tolerance}°</div>${v.reference?`<img src="${v.reference}">`:'<div class="note">No reference image</div>'}<label>Upload / Replace</label><input type="file" accept="image/*" data-ref-file="${v.id}"></div>`).join('');document.querySelectorAll('[data-ref-file]').forEach(inp=>inp.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let v=h.views.find(x=>x.id===inp.dataset.refFile);v.reference=r.result;log(db,currentUser().id,'REFERENCE_IMAGE_UPDATED',`${h.id} ${v.id}`);save();render()};r.readAsDataURL(f)})};$('refHel').onchange=render;$('refreshRef').onclick=render;render()}
function bindRules(){let load=()=>{let h=db.helipads[$('ruleHel').value];$('ruleForm').innerHTML=`<label>Automatic colour</label><select id="rAuto"><option value="1" ${h.autoColour?'selected':''}>ON</option><option value="0" ${!h.autoColour?'selected':''}>OFF</option></select><label>RED below visibility (m)</label><input id="rRed" type="number" value="${h.redVis}"><label>YELLOW below visibility (m)</label><input id="rYellow" type="number" value="${h.yellowVis}"><label>Weather validity (min)</label><input id="rVal" type="number" value="${h.weatherValidityMin}"><label>Concurrent image gap ± minutes</label><input id="rGap" type="number" value="${h.concurrentImageToleranceMin}"><label>Copy colour rules from another helipad</label><select id="copyRuleFrom"><option value="">—</option>${Object.values(db.helipads).filter(x=>x.id!==h.id).map(x=>`<option>${x.id}</option>`).join('')}</select><button class="btn" id="copyRules">COPY RULES</button><button class="btn success full" id="saveRule">PREVIEW & SAVE CHANGES</button>`;$('viewRules').innerHTML=h.views.map(v=>`<div class="grid g3"><div><label>View label</label><input data-vlabel="${v.id}" value="${v.label}"></div><div><label>Bearing</label><input data-vbearing="${v.id}" type="number" value="${v.bearing}"></div><div><label>Tolerance ±°</label><input data-vtol="${v.id}" type="number" value="${v.tolerance}"></div></div>`).join('')+`<button class="btn success full" id="saveViews">SAVE VIEW SETTINGS</button>`;$('copyRules').onclick=()=>{let from=db.helipads[$('copyRuleFrom').value];if(!from)return toast('Select source helipad');h.autoColour=from.autoColour;h.redVis=from.redVis;h.yellowVis=from.yellowVis;h.weatherValidityMin=from.weatherValidityMin;h.concurrentImageToleranceMin=from.concurrentImageToleranceMin;log(db,currentUser().id,'COPY_COLOUR_RULES',`${from.id} -> ${h.id}`);save();load();toast('Rules copied; edit if required')};$('saveRule').onclick=()=>{let old=JSON.stringify({auto:h.autoColour,red:h.redVis,yellow:h.yellowVis,val:h.weatherValidityMin,gap:h.concurrentImageToleranceMin});h.autoColour=$('rAuto').value==='1';h.redVis=+$('rRed').value;h.yellowVis=+$('rYellow').value;h.weatherValidityMin=+$('rVal').value;h.concurrentImageToleranceMin=+$('rGap').value;log(db,currentUser().id,'CHANGE_COLOUR_RULES',`${h.id} ${old} -> ${JSON.stringify({auto:h.autoColour,red:h.redVis,yellow:h.yellowVis,val:h.weatherValidityMin,gap:h.concurrentImageToleranceMin})}`);save();toast('Rules saved; current status recalculated')};$('saveViews').onclick=()=>{h.views.forEach(v=>{v.label=document.querySelector(`[data-vlabel="${v.id}"]`).value;v.bearing=+document.querySelector(`[data-vbearing="${v.id}"]`).value;v.tolerance=+document.querySelector(`[data-vtol="${v.id}"]`).value});log(db,currentUser().id,'CHANGE_BEARING_RULES',h.id);save();toast('View settings saved')}};$('ruleHel').onchange=load;load()}
function bindSchedules(){let render=()=>{$('taskList').innerHTML=taskHtml(db.tasks.sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt)).slice(0,30))};$('createTask').onclick=()=>{let due=$('taskDue').value;if(!due)return toast('Select due time');let hel=$('taskHel').value,type=$('taskType').value,h=db.helipads[hel],assignee=type==='IMAGE'?findAssignedImageUser(h):findAssignedWeatherUser(h);db.tasks.push({id:'TSK-'+Date.now(),helipadId:hel,type,dueAt:new Date(due).toISOString(),reminderAt:new Date(new Date(due)-600000).toISOString(),assignedUserId:assignee,status:'SCHEDULED',createdBy:currentUser().id});log(db,currentUser().id,'CREATE_TASK',`${type} ${hel}`);save();render()};render()}
function findAssignedImageUser(h){if(h.mode==='OUTSTATION')return Object.values(db.users).find(u=>u.role==='OBSERVER'&&u.observerType==='OUTSTATION'&&u.helipads.includes(h.id))?.id||null;return Object.values(db.users).find(u=>u.role==='CAPTURER'&&u.helipads.includes(h.id))?.id||null}function findAssignedWeatherUser(h){return h.mode==='OUTSTATION'?Object.values(db.users).find(u=>u.role==='OBSERVER'&&u.observerType==='OUTSTATION'&&u.helipads.includes(h.id))?.id:null}
function taskHtml(a){return a.length?a.map(t=>`<div class="timelineItem"><b>${t.type} • ${t.helipadId}</b><br>Due ${fmt(t.dueAt)} • ${t.status}<br><small>Assigned: ${t.assignedUserId||'—'} • Reminder: ${tm(t.reminderAt)}</small></div>`).join(''):'No tasks.'}
function bindMessages(){$('sendMsg').onclick=()=>{let text=$('msgText').value.trim(),ex=$('msgExpiry').value;if(!text||!ex)return toast('Message and expiry required');db.messages.unshift({id:'MSG-'+Date.now(),priority:$('msgPriority').value,scope:$('msgScope').value,text,expiresAt:new Date(ex).toISOString(),createdAt:now(),adminId:currentUser().id});log(db,currentUser().id,'SEND_ADMIN_MESSAGE',text);save();showPage('messages')}}
function activeMessagesHtml(){return db.messages.filter(m=>new Date(m.expiresAt)>new Date()).map(m=>`<div class="timelineItem"><b>${m.priority}</b> • expires ${fmt(m.expiresAt)}<br>${esc(m.text)}</div>`).join('')||'No active messages.'}
function latestAlertsHtml(){let a=[];db.tasks.filter(t=>!['COMPLETE','CANCELLED'].includes(t.status)).slice(0,6).forEach(t=>a.push(`<div class="timelineItem"><b>${t.type} • ${t.helipadId}</b><br>Due ${fmt(t.dueAt)} • ${t.status}</div>`));db.messages.filter(m=>new Date(m.expiresAt)>new Date()).slice(0,5).forEach(m=>a.push(`<div class="timelineItem"><b>${m.priority}</b><br>${esc(m.text)}</div>`));return a.join('')||'No active alerts.'}
function bindAudit(){let render=()=>{let q=$('auditSearch').value.toUpperCase();$('auditRows').innerHTML=db.audit.filter(a=>`${a.actor} ${a.action} ${a.detail}`.toUpperCase().includes(q)).slice(0,300).map(a=>`<tr><td>${fmt(a.time)}</td><td>${a.actor}</td><td>${a.action}</td><td>${esc(a.detail)}</td></tr>`).join('')};$('auditSearch').oninput=render;$('exportAudit').onclick=()=>downloadText('awo_audit.xls',toSpreadsheetXml(db.audit.map(a=>({Time:fmt(a.time),Actor:a.actor,Action:a.action,Detail:a.detail}))),'application/vnd.ms-excel');$('printReport').onclick=()=>window.print();render()}
function bindSettings(){$('saveSettings').onclick=()=>{db.settings.airrepValidityMin=+$('airrepVal').value;db.settings.correctionWindowMin=+$('corrWin').value;db.settings.aviatorCooldownMin=+$('cooldown').value;log(db,currentUser().id,'UPDATE_SETTINGS',JSON.stringify(db.settings));save();toast('Settings saved')};$('backupData').onclick=()=>downloadText('awo_backup.json',JSON.stringify(db,null,2),'application/json');$('restoreBtn').onclick=()=>{let f=$('restoreFile').files[0];if(!f)return toast('Choose backup file');let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();toast('Backup restored');route()}catch{toast('Invalid backup')}};r.readAsText(f)};$('saveCal').onclick=()=>{let k=$('calKey').value.trim(),off=+$('calOffset').value;if(!k||!Number.isFinite(off))return toast('Enter device key and offset');db.deviceCal[k]={offset:off,updatedBy:currentUser().id,updatedAt:now()};log(db,currentUser().id,'DEVICE_CALIBRATION',`${k} ${off} hPa`);save();toast('Calibration saved')};$('transferPrimary').onclick=()=>{let me=currentUser(),to=$('primaryTo').value;if(!me.primary)return toast('Only Primary Administrator can transfer authority');if($('primaryPass').value!==me.password)return toast('Incorrect Primary password');if(!to)return toast('Select another Administrator');db.users[to].primary=true;me.primary=false;log(db,me.id,'TRANSFER_PRIMARY_ADMIN',to);save();toast('Primary Administrator transferred');route()}}

function weatherFormHtml(id,src){let prev=latestObservation(id,src),h=db.helipads[id],sel=prev?.weatherCodes||['NIL'];return `<div class="note">Previous values are retained. Submit creates a new complete observation.${prev?`<br><b>Previous:</b> ${fmt(prev.observedAt)} • VIS ${prev.visibility}m • ${(prev.weatherCodes||[]).join(' ')} • ${prev.hillTop} • ${prev.htStatus}${prev.cloudStatus?' + '+prev.cloudStatus:''}`:''}</div>${src==='OUT'?`<label>METAR</label><textarea id="wfMetar">${esc(prev?.metar||'')}</textarea><div id="metarWarn" class="small"></div>`:''}<label>Visibility (metres)</label><select id="wfVis">${[500,800,1000,1500,2000,3000,5000,8000,10000].map(v=>`<option ${+prev?.visibility===v?'selected':''}>${v}</option>`).join('')}<option value="OTHER">OTHER</option></select><input id="wfVisOther" class="hidden" type="number" placeholder="Exact metres"><label>Weather codes (multiple)</label><div class="codeGrid">${WX.map(w=>`<button class="code ${sel.includes(w)?'selected':''}" data-wx="${w}">${w}</button>`).join('')}</div><label>Hill Top</label><div class="choiceRow">${HILL.map(x=>`<button class="choice ${prev?.hillTop===x?'selected':''}" data-hill="${x}">${x}</button>`).join('')}</div><label>HT status (one compulsory)</label><div class="choiceRow">${HT.map(x=>`<button class="choice ${prev?.htStatus===x?'selected':''}" data-ht="${x}">${x}</button>`).join('')}</div><label>AC / ANC (optional, mutually exclusive)</label><div class="choiceRow"><button class="choice ${!prev?.cloudStatus?'selected':''}" data-cloud="">NONE</button><button class="choice ${prev?.cloudStatus==='AC'?'selected':''}" data-cloud="AC">AC</button><button class="choice ${prev?.cloudStatus==='ANC'?'selected':''}" data-cloud="ANC">ANC</button></div><label>Observer colour</label><div class="choiceRow"><button class="choice green ${prev?.observerColour==='GREEN'||!prev?'selected':''}" data-colour="GREEN">GREEN</button><button class="choice yellow ${prev?.observerColour==='YELLOW'?'selected':''}" data-colour="YELLOW">YELLOW</button><button class="choice red ${prev?.observerColour==='RED'?'selected':''}" data-colour="RED">RED</button></div><button class="btn success full" id="wfSubmit" style="margin-top:12px">REVIEW & SUBMIT</button>`}
function renderWeatherForm(container,id,src){$(container).innerHTML=weatherFormHtml(id,src);let one=(sel,attr)=>document.querySelectorAll(sel).forEach(b=>b.onclick=()=>{document.querySelectorAll(sel).forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});one('[data-hill]','hill');one('[data-ht]','ht');one('[data-cloud]','cloud');one('[data-colour]','colour');document.querySelectorAll('[data-wx]').forEach(b=>b.onclick=()=>{if(b.dataset.wx==='NIL'){document.querySelectorAll('[data-wx]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}else{document.querySelector('[data-wx="NIL"]')?.classList.remove('selected');b.classList.toggle('selected')}});$('wfVis').onchange=()=>{$('wfVisOther').classList.toggle('hidden',$('wfVis').value!=='OTHER')};if(src==='OUT'){$('wfMetar').oninput=metarCheck;metarCheck()}$('wfSubmit').onclick=()=>reviewObservation(id,src)}
function metarCheck(){let t=$('wfMetar').value,p=latestObservation(currentUser().helipads[0],'OUT')?.metar||'',w=[];let a=t.match(/\b(\d{6})Z\b/),b=p.match(/\b(\d{6})Z\b/);if(a&&b&&a[1]===b[1])w.push('⚠ CAUTION — METAR TIME UNCHANGED. Please verify.');if(!a)w.push('Check observation time group (DDHHMMZ).');$('metarWarn').innerHTML=w.join('<br>')}
function reviewObservation(id,src){let vis=$('wfVis').value==='OTHER'?+$('wfVisOther').value:+$('wfVis').value,weatherCodes=[...document.querySelectorAll('[data-wx].selected')].map(x=>x.dataset.wx),hillTop=document.querySelector('[data-hill].selected')?.dataset.hill,htStatus=document.querySelector('[data-ht].selected')?.dataset.ht,cloudStatus=document.querySelector('[data-cloud].selected')?.dataset.cloud||'',observerColour=document.querySelector('[data-colour].selected')?.dataset.colour,metar=src==='OUT'?$('wfMetar').value.trim():'';if(!Number.isFinite(vis)||!weatherCodes.length||!hillTop||!htStatus||!observerColour||(src==='OUT'&&!metar))return toast('Complete all required fields');let h=db.helipads[id],data={id:'OBS-'+Date.now(),helipadId:id,sourceUserId:currentUser().id,source:src,observedAt:now(),submittedAt:now(),visibility:vis,weatherCodes,hillTop,htStatus,cloudStatus,observerColour,metar};data.systemColour=calcColour(h,data);openModal('REVIEW SUBMISSION',`<div class="note"><b>${id}</b><br>VIS ${vis} m • ${weatherCodes.join(' ')} • ${hillTop} • ${htStatus}${cloudStatus?' + '+cloudStatus:''}<br>${src==='OUT'?esc(metar):''}<br>Observer: ${observerColour} • System: ${data.systemColour}</div><label><input id="confirmWeather" type="checkbox" checked style="width:auto;min-height:auto"> Submit complete weather observation</label>${src==='OUT'?`<label><input id="confirmImages" type="checkbox" checked disabled style="width:auto;min-height:auto"> Complete required imagery after weather submission</label>`:''}<button class="btn success full" id="finalObs">FINAL SUBMIT</button>`);$('finalObs').onclick=()=>{if(!$('confirmWeather').checked)return toast('Weather submission must be selected');db.observations.push(data);log(db,currentUser().id,'SUBMIT_OBSERVATION',`${id} ${src} ${data.systemColour}`);save();closeModal();toast('Observation submitted');if(src==='IN')showPage('inEntry');else showPage('outCamera')}}
function bindInEntry(){let load=()=>{let id=$('inHel').value,h=db.helipads[id];$('inEntryVisuals').innerHTML=`<div class="grid g2"><div><h3>REFERENCE IMAGES</h3><div class="imgGrid">${h.views.filter(v=>v.reference).map(v=>`<div class="imgCard"><b>${v.label}</b><img src="${v.reference}"></div>`).join('')||'No reference images'}</div></div><div><h3>LATEST IMAGES</h3><div class="imgGrid">${latestImages(id).map(imageCardHtml).join('')||'No latest images'}</div></div></div>`;renderWeatherForm('inForm',id,'IN')};$('inHel').onchange=load;load()}
function bindInImages(){let render=()=>{let h=db.helipads[$('inImgHel').value];$('inImagesBox').innerHTML=`<h3>Reference Images</h3><div class="imgGrid">${h.views.map(v=>`<div class="imgCard"><b>${v.label}</b>${v.reference?`<img src="${v.reference}">`:'<div class="note">No reference</div>'}</div>`).join('')}</div><h3>Latest Images</h3><div class="imgGrid">${latestImages(h.id).map(imageCardHtml).join('')||'No operational images'}</div><button class="btn purple" id="requestReimage">REQUEST NEW IMAGE(S)</button>`;$('requestReimage').onclick=()=>{openModal('REQUEST NEW IMAGES',`<label>Select views</label><div class="assignGrid">${h.views.map(v=>`<button class="chip" data-rv="${v.id}">${v.label}</button>`).join('')}<button class="chip" id="allViews">ALL VIEWS</button></div><label>Optional reason</label><select id="reReason"><option value="">No reason</option><option>Blurred</option><option>Too Dark</option><option>Obstructed</option><option>Wrong View</option><option>Poor Clarity</option><option>Other</option></select><button class="btn success full" id="sendReReq">SEND REQUEST</button>`);document.querySelectorAll('[data-rv]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('allViews').onclick=()=>document.querySelectorAll('[data-rv]').forEach(b=>b.classList.add('on'));$('sendReReq').onclick=()=>{let views=[...document.querySelectorAll('[data-rv].on')].map(x=>x.dataset.rv);if(!views.length)return toast('Select at least one view');db.requests.unshift({id:'REQ-'+Date.now(),type:'IMAGE',helipadId:h.id,views,reason:$('reReason').value,requestedBy:currentUser().id,status:'PENDING',createdAt:now()});log(db,currentUser().id,'REQUEST_NEW_IMAGES',`${h.id} ${views.join(',')}`);save();closeModal();toast('Request sent')}}};$('inImgHel').onchange=render;render()}
function observerHistory(src){let u=currentUser(),a=db.observations.filter(o=>o.source===src&&o.sourceUserId===u.id).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt));return pageTitle('WEATHER / IMAGE HISTORY')+`<div class="card"><div class="cardBody">${a.map(o=>`<div class="timelineItem"><b>${o.helipadId} • ${o.systemColour}</b> — ${fmt(o.observedAt)}<br><small>VIS ${o.visibility} • ${(o.weatherCodes||[]).join(' ')} • ${o.hillTop} • ${o.htStatus}</small></div>`).join('')||'No history.'}</div></div>`}

function imageCardHtml(i){return `<div class="imgCard"><b>${i.viewLabel}</b><img src="${i.dataUrl}"><small>${fmt(i.capturedAt)} • ${i.bearing==null?'OVERRIDE':i.bearing+'° '+dirFromBearing(i.bearing)} • ${i.capturedBy}</small></div>`}

let cam={stream:null,facing:'environment',bearing:null,view:null,helipad:null,override:false,overrideReason:'',photo:null,sessionId:null};
async function openCameraFor(viewId){let u=currentUser(),h=db.helipads[(u.helipads||[])[0]],v=h?.views.find(x=>x.id===viewId);if(!h||!v)return;cam.helipad=h;cam.view=v;cam.override=false;cam.photo=null;if(!cam.sessionId)cam.sessionId='SES-'+Date.now();$('cameraTarget').textContent=`TARGET ${v.bearing}° ${dirFromBearing(v.bearing)} • ±${v.tolerance}°`;$('cameraModal').classList.remove('hidden');$('cameraReview').classList.add('hidden');$('cameraStage').classList.remove('hidden');updateWeatherStrip();try{cam.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:cam.facing}},audio:false});$('cameraVideo').srcObject=cam.stream}catch(e){toast('Camera permission unavailable. Use HTTPS and allow camera.',true)}startOrientation();drawRadial()}
function stopCamera(){if(cam.stream)cam.stream.getTracks().forEach(t=>t.stop());cam.stream=null;$('cameraModal').classList.add('hidden')}
$('closeCamera').onclick=stopCamera;$('referenceBtn').onclick=()=>{if(cam.view?.reference)openModal('REFERENCE — '+cam.view.label,`<img src="${cam.view.reference}" style="width:100%;max-height:75vh;object-fit:contain">`);else toast('No reference image uploaded')};$('switchBtn').onclick=async()=>{cam.facing=cam.facing==='environment'?'user':'environment';if(cam.stream)cam.stream.getTracks().forEach(t=>t.stop());try{cam.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:cam.facing},audio:false});$('cameraVideo').srcObject=cam.stream}catch{toast('Unable to switch camera')}};$('overrideBtn').onclick=()=>openModal('BEARING OVERRIDE',`<label>Reason (mandatory)</label><select id="ovReason"><option>Compass/Sensor Issue</option><option>Physical Obstruction</option><option>Safety/Access Restriction</option><option>Other</option></select><button id="confirmOverride" class="btn warn full">CONFIRM OVERRIDE</button>`);document.addEventListener('click',e=>{if(e.target.id==='confirmOverride'){cam.override=true;cam.overrideReason=$('ovReason').value;closeModal();toast('Bearing override enabled')}})
function startOrientation(){let handler=e=>{let b=null;if(typeof e.webkitCompassHeading==='number')b=e.webkitCompassHeading;else if(e.alpha!=null)b=(360-e.alpha+360)%360;if(b!=null){cam.bearing=Math.round(b);updateGuide();drawRadial()}};if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')DeviceOrientationEvent.requestPermission().then(x=>{if(x==='granted')window.addEventListener('deviceorientation',handler,true)}).catch(()=>{});else{window.addEventListener('deviceorientationabsolute',handler,true);window.addEventListener('deviceorientation',handler,true)}}
function updateGuide(){let target=cam.view?.bearing??0,b=cam.bearing;if(b==null){$('bearingValue').textContent='—°';$('bearingDir').textContent='COMPASS UNAVAILABLE';$('guideTitle').textContent='COMPASS UNAVAILABLE';$('guideArrows').textContent='';$('guide').className='guide out';return}let d=angleDiff(target,b),ad=Math.abs(d),tol=cam.view.tolerance;$('bearingValue').textContent=b+'°';$('bearingDir').textContent=dirFromBearing(b);if(ad<=tol){$('guide').className='guide in';$('guideTitle').textContent='ALIGNED — HOLD STEADY';$('guideArrows').textContent='✓';$('guideSub').textContent='IN RANGE'}else if(ad<=tol+15){$('guide').className='guide near';$('guideTitle').textContent=d>0?'SLIGHTLY RIGHT':'SLIGHTLY LEFT';$('guideArrows').textContent=d>0?'››':'‹‹';$('guideSub').textContent='NEAR TARGET'}else{$('guide').className='guide out';$('guideTitle').textContent=d>0?'TURN RIGHT':'TURN LEFT';$('guideArrows').textContent=d>0?'›››':'‹‹‹';$('guideSub').textContent='MOVE SLOWLY'}}
function drawRadial(ctx=$('radialCanvas').getContext('2d'),w=$('radialCanvas').width,h=$('radialCanvas').height,b=cam.bearing??0,target=cam.view?.bearing??0){ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h-10);ctx.strokeStyle='rgba(255,255,255,.9)';ctx.fillStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,w*.42,Math.PI*1.08,Math.PI*1.92);ctx.stroke();for(let off=-60;off<=60;off+=10){let ang=((off-90)*Math.PI/180),r=w*.42,x=Math.cos(ang)*r,y=Math.sin(ang)*r;ctx.beginPath();ctx.moveTo(x*.96,y*.96);ctx.lineTo(x,y);ctx.stroke();ctx.font='34px Arial';ctx.textAlign='center';ctx.fillText(String((Math.round(b/10)*10+off+360)%360).padStart(3,'0')+'°',Math.cos(ang)*r*.82,Math.sin(ang)*r*.82)}let diff=angleDiff(target,b),ang=((diff-90)*Math.PI/180);ctx.strokeStyle='#ffd21f';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(Math.cos(ang)*w*.33,Math.sin(ang)*w*.33);ctx.lineTo(Math.cos(ang)*w*.43,Math.sin(ang)*w*.43);ctx.stroke();ctx.restore()}
function updateWeatherStrip(){let o=officialObservation(cam.helipad),s=statusFor(cam.helipad),parts=[`HELIPAD ${cam.helipad.id}`,`VIEW ${cam.view.label}`];if(o)parts.push(`VIS ${o.visibility}m`,`WX ${(o.weatherCodes||[]).join(' ')}`,`HILL ${o.hillTop}`,`HT ${o.htStatus}`,`STATUS ${s.status}`);$('weatherStrip').innerHTML=parts.map(x=>`<span>${esc(x)}</span>`).join('')}
$('shutterBtn').onclick=()=>capturePhoto();function capturePhoto(){let video=$('cameraVideo');if(!video.videoWidth)return toast('Camera not ready');let diff=cam.bearing==null?999:Math.abs(angleDiff(cam.view.bearing,cam.bearing)),inRange=diff<=cam.view.tolerance;if(!inRange&&!cam.override)return toast('Move into bearing tolerance or use Bearing Override',true);let c=$('captureCanvas'),ctx=c.getContext('2d'),w=video.videoWidth,h=video.videoHeight;c.width=w;c.height=h;ctx.drawImage(video,0,0,w,h);embedOverlay(ctx,w,h,inRange);cam.photo=c.toDataURL('image/jpeg',.78);$('reviewImage').src=cam.photo;$('reviewMeta').innerHTML=`<b>${cam.helipad.id} • ${cam.view.label}</b><br>Captured: ${new Date().toLocaleString()}<br>Bearing: ${cam.bearing==null?'UNAVAILABLE':cam.bearing+'° '+dirFromBearing(cam.bearing)} • Target ${cam.view.bearing}° ±${cam.view.tolerance}°<br>Status: ${inRange?'IN RANGE':'BEARING OVERRIDE'} ${cam.override?`• ${esc(cam.overrideReason)}`:''}`;$('cameraStage').classList.add('hidden');$('cameraReview').classList.remove('hidden')}
function embedOverlay(ctx,w,h,inRange){ctx.save();let scale=Math.max(.8,w/1400);ctx.fillStyle='rgba(3,15,27,.78)';ctx.fillRect(20,20,w*.52,85*scale);ctx.fillStyle='#fff';ctx.font=`bold ${28*scale}px Arial`;ctx.fillText(`${cam.helipad.id} — ${cam.view.label}`,40,58*scale);ctx.fillStyle='#ffd21f';ctx.font=`bold ${22*scale}px Arial`;ctx.fillText(`TARGET ${cam.view.bearing}° ${dirFromBearing(cam.view.bearing)} • ±${cam.view.tolerance}°`,40,90*scale);let o=officialObservation(cam.helipad),s=statusFor(cam.helipad);let barH=100*scale;ctx.fillStyle='rgba(3,15,27,.82)';ctx.fillRect(20,h-barH-20,w-40,barH);ctx.fillStyle='#fff';ctx.font=`bold ${20*scale}px Arial`;let info=[];if(o)info=[`VIS ${o.visibility} m`,`WX ${(o.weatherCodes||[]).join(' ')}`,`HILL ${o.hillTop}`,`HT ${o.htStatus}`,`STATUS ${s.status}`];else info=['NO VALID WEATHER'];let x=40;for(let item of info){ctx.fillText(item,x,h-55*scale);x+=ctx.measureText(item).width+42*scale}ctx.fillStyle='#ffd21f';ctx.font=`bold ${46*scale}px Arial`;let btxt=cam.bearing==null?'BEARING OVERRIDE':`${cam.bearing}° ${dirFromBearing(cam.bearing)}`;ctx.fillText(btxt,w*.42,h*.72);ctx.fillStyle='#fff';ctx.font=`${18*scale}px Arial`;if(o?.metar){ctx.fillStyle='rgba(3,15,27,.86)';ctx.fillRect(20,h-barH-58*scale,w-40,34*scale);ctx.fillStyle='#fff';ctx.font=`${15*scale}px Arial`;ctx.fillText('METAR '+o.metar.slice(0,120),40,h-barH-34*scale)}ctx.fillStyle='#fff';ctx.font=`${18*scale}px Arial`;ctx.fillText(new Date().toLocaleString(),40,h-20);ctx.fillText(currentUser().id,w*.72,h-20);ctx.restore()}
$('retakeBtn').onclick=()=>{$('cameraReview').classList.add('hidden');$('cameraStage').classList.remove('hidden');cam.photo=null};$('usePhotoBtn').onclick=()=>{let u=currentUser(),source=u.role==='OBSERVER'?'OUT':'CAP',sid=cam.sessionId||('SES-'+Date.now()),hadPrevious=latestImages(cam.helipad.id).length>0,meta={id:'IMG-'+Date.now(),sessionId:sid,helipadId:cam.helipad.id,viewId:cam.view.id,viewLabel:cam.view.label,capturedBy:u.id,source,capturedAt:now(),submittedAt:now(),bearing:cam.bearing,targetBearing:cam.view.bearing,tolerance:cam.view.tolerance,bearingOverride:cam.override,overrideReason:cam.overrideReason,dataUrl:cam.photo};db.images.push(meta);let ses=db.sessions.find(x=>x.id===sid);if(!ses){ses={id:sid,helipadId:cam.helipad.id,userId:u.id,source,submittedAt:now(),complete:false,scheduled:false};db.sessions.push(ses)}let same=db.images.filter(i=>i.sessionId===sid),required=cam.helipad.views.filter(v=>v.active!==false).length;ses.complete=new Set(same.map(i=>i.viewId)).size>=required;if(hadPrevious&&!ses.complete)cam.helipad.mixedLatched=true;if(ses.complete){let task=db.tasks.find(t=>t.type==='IMAGE'&&t.helipadId===cam.helipad.id&&!['COMPLETE','CANCELLED'].includes(t.status)&&Math.abs(new Date(t.dueAt)-Date.now())<=60*60000);if(task){ses.scheduled=true;task.status='COMPLETE';task.completedAt=now();cam.helipad.mixedLatched=false}cam.sessionId=null}log(db,u.id,'CAPTURE_IMAGE',`${cam.helipad.id} ${cam.view.id} ${cam.bearing??'OVERRIDE'}`);save();stopCamera();toast('Image saved and available immediately');showPage(u.role==='CAPTURER'?'capHome':'outCamera')}

function bindAvHome(){let render=()=>{let u=currentUser(),q=$('avSearch').value.toUpperCase(),f=$('avFilter').value,shown=u.displayHelipads||u.helipads;$('avRows').innerHTML=shown.filter(id=>id.includes(q)).map(id=>db.helipads[id]).filter(Boolean).filter(h=>f==='ALL'||statusFor(h).status===f).map(h=>{let s=statusFor(h),o=s.obs;return `<tr class="clickable" data-avhel="${h.id}"><td><b>${h.name}</b></td><td>${o?.visibility??'—'}</td><td>${o?(o.weatherCodes||[]).join(' '):'—'}</td><td>${o?.hillTop??'—'}</td><td>${o?.htStatus??'—'}</td><td>${o?.cloudStatus||''}</td><td class="status-${s.status}">${s.status}</td><td>${o?.source??'—'}</td><td>📷 ${imageStatus(h)}</td><td>${tm(o?.observedAt)}</td></tr>`}).join('');document.querySelectorAll('[data-avhel]').forEach(r=>r.onclick=()=>aviatorDetail(r.dataset.avhel))};$('avSearch').oninput=render;$('avFilter').onchange=render;$('manageAvHel').onclick=()=>manageAviatorDisplay();render()}
function manageAviatorDisplay(){let u=currentUser(),shown=u.displayHelipads||[...u.helipads];openModal('DISPLAYED HELIPADS',`<div class="assignGrid">${u.helipads.map(id=>`<button class="chip ${shown.includes(id)?'on':''}" data-disp="${id}">${id}</button>`).join('')}</div><button class="btn success full" id="saveDisp">SAVE</button>`);document.querySelectorAll('[data-disp]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('saveDisp').onclick=()=>{u.displayHelipads=[...document.querySelectorAll('[data-disp].on')].map(x=>x.dataset.disp);save();closeModal();showPage('avHome')}}
function aviatorDetail(id){let h=db.helipads[id],s=statusFor(h),o=s.obs,imgs=latestImages(id),hist=db.observations.filter(x=>x.helipadId===id).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt)).slice(0,5),ars=db.airreps.filter(a=>[a.from,a.to].includes(id)&&new Date(a.expiresAt)>new Date()).sort((a,b)=>new Date(b.submittedAt)-new Date(a.submittedAt));openModal(h.name,`<div class="tabs"><button class="tab active">OVERVIEW</button></div><div class="grid g2"><div><div class="timelineItem status-${s.status}"><b>${s.status}</b><br>${o?`VIS ${o.visibility}m • ${(o.weatherCodes||[]).join(' ')} • ${o.hillTop} • ${o.htStatus}`:'NO VALID WEATHER'}</div><h3>VALID AIRREPs</h3>${ars.map(a=>`<div class="timelineItem"><b>${a.from} → ${a.to}</b><br>${esc(a.remarks)}<br><small>${fmt(a.submittedAt)} • ${a.aviatorId}</small></div>`).join('')||'None'}</div><div><h3>REFERENCE IMAGES</h3><div class="imgGrid">${h.views.map(v=>`<div class="imgCard"><b>${v.label}</b>${v.reference?`<img src="${v.reference}">`:'No reference'}</div>`).join('')}</div></div></div><h3>LATEST OPERATIONAL IMAGES — ${imageStatus(h)}</h3><div class="imgGrid">${imgs.map(imageCardHtml).join('')||'No image'}</div><h3>PREVIOUS 5 WEATHER OBSERVATIONS</h3>${hist.map(x=>`<div class="timelineItem"><b>${fmt(x.observedAt)} • ${x.systemColour}</b><br>VIS ${x.visibility} • ${(x.weatherCodes||[]).join(' ')} • ${x.hillTop} • ${x.htStatus}</div>`).join('')}<div class="row"><button class="btn primary" id="avReqLatest">REQUEST LATEST IMAGE</button><button class="btn" id="avNotif">NOTIFICATION SETTINGS</button></div>`);$('avReqLatest').onclick=()=>requestLatestImage(id);$('avNotif').onclick=()=>openAlertSettings(id)}
function requestLatestImage(id){let u=currentUser(),last=db.requests.find(r=>r.requestedBy===u.id&&r.helipadId===id&&r.status==='PENDING');if(last&&Date.now()-new Date(last.createdAt)<db.settings.aviatorCooldownMin*60000)return toast('Existing request is still pending');let h=db.helipads[id];openModal('REQUEST LATEST IMAGE',`<div class="assignGrid">${h.views.map(v=>`<button class="chip" data-rview="${v.id}">${v.label}</button>`).join('')}<button class="chip" id="allR">ALL VIEWS</button></div><label>Optional reason</label><textarea id="rMsg"></textarea><button class="btn success full" id="sendImgReq">SEND REQUEST</button>`);document.querySelectorAll('[data-rview]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('allR').onclick=()=>document.querySelectorAll('[data-rview]').forEach(b=>b.classList.add('on'));$('sendImgReq').onclick=()=>{let views=[...document.querySelectorAll('[data-rview].on')].map(x=>x.dataset.rview);if(!views.length)return toast('Select view(s)');db.requests.unshift({id:'REQ-'+Date.now(),type:'IMAGE',helipadId:id,views,reason:$('rMsg').value,requestedBy:u.id,status:'PENDING',createdAt:now()});log(db,u.id,'AVIATOR_REQUEST_IMAGE',`${id} ${views.join(',')}`);save();closeModal();toast('Request sent')}}
function openAlertSettings(id){let u=currentUser();u.alerts=u.alerts||{};let a=u.alerts[id]||{statuses:['RED','PURPLE'],returnGreen:false,audible:false};openModal('NOTIFICATIONS — '+id,`<label>Status notifications</label><div class="assignGrid">${['YELLOW','RED','GREY','PURPLE'].map(s=>`<button class="chip ${a.statuses.includes(s)?'on':''}" data-ast="${s}">${s}</button>`).join('')}</div><label><input id="retGreen" type="checkbox" ${a.returnGreen?'checked':''} style="width:auto;min-height:auto"> Notify when status returns to GREEN</label><label><input id="audible" type="checkbox" ${a.audible?'checked':''} style="width:auto;min-height:auto"> Audible / ringing alert</label><button class="btn success full" id="saveAlert">SAVE</button>`);document.querySelectorAll('[data-ast]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('saveAlert').onclick=()=>{u.alerts[id]={statuses:[...document.querySelectorAll('[data-ast].on')].map(x=>x.dataset.ast),returnGreen:$('retGreen').checked,audible:$('audible').checked};save();closeModal();toast('Alert settings saved')}}
function bindAirrep(){$('submitAirrep').onclick=()=>{let from=$('arFrom').value,to=$('arTo').value;if(from===to)return toast('Select two different helipads');let a={id:'AR-'+Date.now(),aviatorId:currentUser().id,from,to,remarks:$('arRemarks').value.trim(),t1:$('arT1').value,pType1:$('arPType1').value,p1:$('arP1').value,t2:$('arT2').value,pType2:$('arPType2').value,p2:$('arP2').value,submittedAt:now(),expiresAt:new Date(Date.now()+db.settings.airrepValidityMin*60000).toISOString()};db.airreps.unshift(a);log(db,currentUser().id,'SUBMIT_AIRREP',`${from}->${to}`);save();toast('AIRREP submitted');showPage('avAirrep')}}
function airrepCards(){return db.airreps.slice(0,20).map(a=>`<div class="timelineItem"><b>${a.from} → ${a.to}</b><br>${esc(a.remarks)}<br><small>${a.t1}°C / ${a.p1} ${a.pType1} • ${a.t2}°C / ${a.p2} ${a.pType2} • ${fmt(a.submittedAt)}</small></div>`).join('')||'No AIRREPs.'}
function airrepTable(admin=false){return `<div class="card"><div class="cardBody"><div class="tableWrap"><table><thead><tr><th>TIME</th><th>FROM</th><th>TO</th><th>AVIATOR</th><th>REMARKS</th><th>VALID</th></tr></thead><tbody>${db.airreps.map(a=>`<tr><td>${fmt(a.submittedAt)}</td><td>${a.from}</td><td>${a.to}</td><td>${a.aviatorId}</td><td>${esc(a.remarks)}</td><td>${new Date(a.expiresAt)>new Date()?'YES':'OLD AIRREP'}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function bindCompare(){let sel=[];document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{b.classList.toggle('on');sel=[...document.querySelectorAll('[data-compare].on')].map(x=>x.dataset.compare)});$('doCompare').onclick=()=>{if(sel.length<2)return toast('Select at least two helipads');$('compareResult').innerHTML=`<div class="tableWrap"><table><thead><tr><th>HELIPAD</th><th>VIS</th><th>WX</th><th>HILL</th><th>STATUS</th><th>IMAGE</th></tr></thead><tbody>${sel.map(id=>{let h=db.helipads[id],s=statusFor(h),o=s.obs;return `<tr><td>${id}</td><td>${o?.visibility??'—'}</td><td>${o?(o.weatherCodes||[]).join(' '):'—'}</td><td>${o?.hillTop??'—'}</td><td class="status-${s.status}">${s.status}</td><td>${imageStatus(h)}</td></tr>`}).join('')}</tbody></table></div>${$('compareImages').checked?`<div class="grid g2" style="margin-top:10px">${sel.map(id=>`<div><h3>${id}</h3><div class="imgGrid">${latestImages(id).map(imageCardHtml).join('')||'No images'}</div></div>`).join('')}</div>`:''}`}}
function bindAvAlerts(){let u=currentUser();let render=()=>{$('avAlertList').innerHTML=u.helipads.map(id=>{let a=u.alerts?.[id];return `<div class="timelineItem"><b>${id}</b><br>${a?`Statuses: ${a.statuses.join(', ')} • Return Green: ${a.returnGreen?'YES':'NO'} • ${a.audible?'AUDIBLE':'NORMAL'}`:'No personal alerts'}<br><button class="btn" data-edit-alert="${id}">EDIT</button></div>`}).join('');document.querySelectorAll('[data-edit-alert]').forEach(b=>b.onclick=()=>openAlertSettings(b.dataset.editAlert));$('profileList').innerHTML=db.profiles.filter(p=>p.owner===u.id).map(p=>`<div class="timelineItem"><b>${p.name}</b> • ${p.active?'ACTIVE':'OFF'}<br><button class="btn" data-toggle-prof="${p.id}">${p.active?'DEACTIVATE':'ACTIVATE'}</button></div>`).join('')||'No profiles.';document.querySelectorAll('[data-toggle-prof]').forEach(b=>b.onclick=()=>{let p=db.profiles.find(x=>x.id===b.dataset.toggleProf);p.active=!p.active;save();render()})};$('saveProfile').onclick=()=>{let name=$('profileName').value.trim();if(!name)return toast('Enter profile name');db.profiles.push({id:'PROF-'+Date.now(),owner:u.id,name,active:false,alerts:JSON.parse(JSON.stringify(u.alerts||{})),sharedFrom:null});save();render()};render()}
function bindPeer(){let render=()=>{let u=currentUser(),a=db.peerRequests.filter(r=>r.to===u.id||r.from===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));$('peerList').innerHTML=a.map(r=>`<div class="timelineItem"><b>${r.from} → ${r.to} • ${r.helipadId}</b><br>${r.type} • ${r.status}<br><small>${esc(r.message||'')}</small>${r.to===u.id&&r.status==='PENDING'?`<div class="row"><button class="btn success" data-peer-accept="${r.id}">ACCEPT</button><button class="btn danger" data-peer-reject="${r.id}">REJECT</button></div>`:''}</div>`).join('')||'No pilot-to-pilot requests.';document.querySelectorAll('[data-peer-accept]').forEach(b=>b.onclick=()=>{let r=db.peerRequests.find(x=>x.id===b.dataset.peerAccept);r.status='ACCEPTED';r.respondedAt=now();save();render();toast('Request accepted')});document.querySelectorAll('[data-peer-reject]').forEach(b=>b.onclick=()=>{let r=db.peerRequests.find(x=>x.id===b.dataset.peerReject);r.status='REJECTED';r.respondedAt=now();save();render()})};$('sendPeer').onclick=()=>{let to=$('peerTo').value;if(!to)return toast('No eligible Aviator');db.peerRequests.unshift({id:'PEER-'+Date.now(),from:currentUser().id,to,helipadId:$('peerHel').value,type:$('peerType').value,message:$('peerMsg').value,status:'PENDING',createdAt:now()});log(db,currentUser().id,'PILOT_TO_PILOT_REQUEST',`${to} ${$('peerHel').value}`);save();render();toast('Request sent')};render()}

function refreshNotifications(){let u=currentUser();if(!u)return;let due=db.tasks.filter(t=>t.assignedUserId===u.id&&!['COMPLETE','CANCELLED'].includes(t.status)&&new Date(t.reminderAt)<=new Date()&&new Date(t.dueAt)>=new Date(Date.now()-3600000));due.forEach(t=>{if(!t._shown){t._shown=true;toast(`${t.type} due at ${tm(t.dueAt)} — ${t.helipadId}`,true)}});db.messages.filter(m=>new Date(m.expiresAt)>new Date()&&(m.scope==='ALL'||m.scope===u.role)).forEach(m=>{if(!m.seenBy?.includes(u.id)){m.seenBy=m.seenBy||[];m.seenBy.push(u.id);toast(`${m.priority}: ${m.text}`,m.priority==='URGENT')}});save()}
setInterval(refreshNotifications,30000);window.addEventListener('online',()=>{$('syncBadge').textContent='ONLINE • LOCAL MODE';toast('Connection available')});window.addEventListener('offline',()=>{$('syncBadge').textContent='OFFLINE READY'});
function downloadText(name,text,type='text/plain'){let b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toSpreadsheetXml(rows){let keys=rows.length?Object.keys(rows[0]):[];let cells=keys.map(k=>`<Cell><Data ss:Type="String">${esc(k)}</Data></Cell>`).join('');let body=rows.map(r=>`<Row>${keys.map(k=>`<Cell><Data ss:Type="String">${esc(r[k])}</Data></Cell>`).join('')}</Row>`).join('');return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Audit"><Table><Row>${cells}</Row>${body}</Table></Worksheet></Workbook>`}
save();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=4.0.0').catch(()=>{}));
route();
